import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import Header from "@/components/header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="w-[92%] mx-auto">
                    <header className="w-max mx-auto my-3">
                        <Header />
                    </header>
                    <main>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    )
}
